name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Maximize build space
      uses: AdityaGarg8/remove-unwanted-software@v3
      with:
        remove-android: 'true'
        remove-dotnet: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-large-packages: 'true'
        remove-cached-tools: 'true'
        remove-swapfile: 'true'
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Specify the version of Python you need

    - name: Install gdown
      run: |
        python -m pip install --upgrade pip
        pip install gdown

    - name: Download file with gdown
      run: gdown https://drive.google.com/uc?id=1UCBpkqe5-IhlnLIZpyfHgsYYYe0LgGku
      
    - name: Unzip checkpoints.zip
      run: unzip checkpoints.zip

    - name: Delete checkpoints.zip
      run: rm checkpoints.zip

    - name: Delete unnecessary checkpoints
      run: rm -r checkpoints/proteinbert*
      
    - name: Move checkpoints folder to flask-server/model
      run: mv checkpoints flask-server/model/

    - name: Change directory to server folder
      run: cd flask-server

    - name: ls
      run: ls .
      
    - name: Build the Docker image
      run: docker build flask-server --file flask-server/Dockerfile --tag dkz-backend:latest

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push image to Docker Hub
      run: docker push dkz-backend:latest
